module.exports = {
    langEN:{
    playHelp: "Queue a song/playlist by URL or name.",
    helpHelp: "Help for commands.",
    pauseHelp: "Pauses playing music.",
    resumeHelp: "Resumes a paused queue.",
    leaveHelp: "Leaves the voice channel.",
    queueHelp: "View the current queue.",
    npHelp: "Shows the now playing text.",
    loopHelp: "Shows the now playing text.",
    searchHelp: "Searchs for up to 10 videos from YouTube.",
    clearHelp: "Clears the entire queue.",
    volumeHelp: "Changes the volume output of the bot.",
    removeHelp: "Remove a song from the queue by position in the queue.",
    skipHelp: "Skip a song or songs with `skip [number]`",
    cooldownWait: "You must wait to use music commands again.",
    notInVC: "You're not in a voice channel.",
    noMusicPlayed: "No music being played.",
    vcMismatch: "You must be in the same voice channel as me.",
    pauseReject: "You cannot pause queues.",
    skipped: "Skipped song.",
    paused: "Playback paused.",
    noVideo: 'No video specified!',
    maxQueue: 'Maximum queue size reached!',
    playlistSearching: "Searching playlist items~",
    playlistFetchErr: "Something went wrong fetching that playlist!",
    playlistFetchZero: "Couldn't get any videos from that playlist.",
    playlistFetchOverLimit: "Too many videos to queue. A maximum of 50 is allowed.",
    playlistQueuedOne: "Queued one song.",
    playlistQueued: "Queued ",
    playlistSongs: " songs.",
    playSearching: "Searching ",
    fail: "Something went wrong. Try again!",
    queueAdd: "Adding To Queue",
    queuedOn: "Queued On",
    requestedBy: "Requested by ",
    requestedByWithoutSpace: "Requested by",
    nowPlaying: "Now Playing",
    commands: "Commands",
    use: "Use "
  }
}
